Use alpine instead of alpine.
Update aria2, webui-aria2 and vsftpd.

Add LICENSE.

Add README.

diff --git a/src/bin/deluser-seedbox b/src/bin/deluser-seedbox
--- a/src/bin/deluser-seedbox
+++ b/src/bin/deluser-seedbox
@@ -1,11 +1,12 @@
-#!/bin/bash
+#!/bin/sh
 set -e
 
-usage() {
+fail() {
+    echo $1 >&2
     echo "$0 [USER]" >&2
     exit 1
 }
 
-[[ -z $1 ]] && echo "Argument USER is missing." >&2 && usage
+[[ -z $1 ]] && fail "Argument USER is missing."
 
 sed -i "/^$1:/ d" /etc/seedbox/users
